# Generated by Django 3.2.4 on 2021-07-10 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('vote_average', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(default=None, max_length=200)),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
